const Database = [
  {
    image: './user1.jpg',
    username: 'Kevin0114',
    postImage: ['./post1.jpg', './post1_2.jpg', './post1_3.jpg'],
    createAt: '',
    caption: 'Enjoying life ☀️',
  },
  {
    image: './user2.PNG',
    username: 'shirleyyy116',
    postImage: ['./post2.jpg'],
    createAt: '',
    caption: 'It\'s a beautiful day!',
  },
  {
    image: './user3.jpg',
    username: 'jackchai_',
    postImage: ['./post3.jpg'],
    createAt: '',
    caption: '',
  },
  {
    image: './user4.svg',
    username: 'goodintroverperson',
    postImage: ['./post4.jpg'], // 加入圖片欄位（隨意範例圖片）
    createAt: '',
    caption: 'Being an introvert is cool.',
  },
  {
    image: './user5.svg',
    username: 'love_to_eat',
    postImage: ['./post5.jpg'],
    createAt: '',
    caption: 'Food is life!',
  },
  {
    image: './user6.svg',
    username: 'pdkslafjow',
    postImage: ['./post6.jpg'],
    createAt: '',
    caption: 'Adventures await!',
  },
  {
    image: './user7.png',
    username: 'angelisme___',
    postImage: ['./post7.gif'],
    createAt: '',
    caption: 'Spreading positivity ✨',
  },
  {
    image: './user8.jpg',
    username: 'helloworld_',
    postImage: ['./post8.jpg'],
    createAt: '',
    caption: 'Starting a new journey.',
  },
  {
    image: './user9.jpg',
    username: '_tody_is_not_my_day',
    postImage: ['./post9.jpg'],
    createAt: '',
    caption: 'Bad day, but still smiling!',
  },
  {
    image: './user10.jpg',
    username: 'i_hate_towork',
    postImage: ['./post10.jpg'],
    createAt: '',
    caption: 'Monday blues...',
  },
  {
    image: './user11.jpg',
    username: 'omg_im_duck',
    postImage: ['./post11.jpg'],
    createAt: '',
    caption: 'Quack quack 🦆',
  },
  {
    image: './user12.jpg',
    username: '114357_windy',
    postImage: ['./post12.jpg'],
    createAt: '',
    caption: 'Feeling the wind in my hair 🍃',
  },
  {
    image: './user13.jpg',
    username: 'Deutschland123',
    postImage: ['./post13.jpg'],
    createAt: '',
    caption: 'Germany vibes 🇩🇪',
  },
  {
    image: './user14.jpg',
    username: '1205_fig',
    postImage: ['./post14.jpg'],
    createAt: '',
    caption: 'Exploring nature 🌿',
  },
  {
    image: './user15.jpg',
    username: 'lemonad_to_cute',
    postImage: ['./post15.jpg'],
    createAt: '',
    caption: 'Life is better with lemonade 🍋',
  },
  {
    image: './user16.svg',
    username: 'Aolicefs',
    postImage: ['./post16_1.jpg','./post16_2.jpg'],
    createAt: '',
    caption: 'Creating art 🎨',
  },
  {
    image: './user17.jpg',
    username: 'wowwgoodjack',
    postImage: ['./post17_1.jpg','./post17_2.jpg'],
    createAt: '',
    caption: 'Good vibes only ✌️ wowwwwww yoooo ✌️✌️✌️',
  },
];

export default Database;
